version: '3.1'
services:
  stats-server:
    build: stats
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - stats-db

  stats-db:
    image: postgres
    container_name: stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - STATS-SERVICE-URL=http://stats-server:9090
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres
    container_name: ewm_service_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_service_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root